#!/bin/bash
echo "Enter a five-digit number:"
read number
if [[ $number =~ ^[0-9]{5}$ ]]; then
    reversed=$(echo $number | rev)
    echo "The reverse of the number is: $reversed"
else
    echo "Error: Please enter a valid five-digit number."
fi
