#!/bin/bash
current_date_time=$(date)
current_user=$(whoam)
current_directory=$(pwd)
echo "Current Date and Time: $current_date_time"
echo "Username: $current_user"
echo "Current Working Directory: $current_directory"
