#!/bin/bash

echo "Enter a string:"
read input
reverse=$(echo "$input" | rev)
if [ "$input" == "$reverse" ]; then
    echo "The string '$input' is a palindrome."
else
    echo "The string '$input' is not a palindrome."
fi
