#!/bin/bash

echo "Enter a password:"
read password

if [[ ${#password} -ge 8]]; then
    echo "Password is strong."
else
    echo "Password is weak. Make sure it has at least 8 characters, including uppercase, lowercase, numbers, and special characters."
fi
